#pragma once

enum ERenderStencilOp
{
	RENDER_STENCIL_OP_KEEP = 1,
	RENDER_STENCIL_OP_ZERO = 2,
	RENDER_STENCIL_OP_REPLACE = 3,
	RENDER_STENCIL_OP_INCR_SAT = 4,
	RENDER_STENCIL_OP_DECR_SAT = 5,
	RENDER_STENCIL_OP_INVERT = 6,
	RENDER_STENCIL_OP_INCR = 7,
	RENDER_STENCIL_OP_DECR = 8
};
