#pragma once

enum ERenderStencilOp : __int32
{
    RENDER_STENCIL_OP_KEEP = 0x1,
    RENDER_STENCIL_OP_ZERO = 0x2,
    RENDER_STENCIL_OP_REPLACE = 0x3,
    RENDER_STENCIL_OP_INCR_SAT = 0x4,
    RENDER_STENCIL_OP_DECR_SAT = 0x5,
    RENDER_STENCIL_OP_INVERT = 0x6,
    RENDER_STENCIL_OP_INCR = 0x7,
    RENDER_STENCIL_OP_DECR = 0x8
};
