#pragma once

enum ERenderGlowTypes : __int32
{
    ERENDERGLOWTYPE_NONE = 0x0,
    ERENDERGLOWTYPE_ENEMIES = 0x1,
    ERENDERGLOWTYPE_ALLIES = 0x2,
    ERENDERGLOWTYPE_ITEMS = 0x3,
    ERENDERGLOWTYPE_BACKGROUND = 0x4,
    ERENDERGLOWTYPE_CONTRACT_TARGET = 0x5,
    ERENDERGLOWTYPE_OBJECTIVES = 0x6,
    ERENDERGLOWTYPE_BREADCRUMB = 0x7,
    ERENDERGLOWTYPE_BACKGROUNDUNMASKED = 0x8,
    ERENDERGLOWTYPE_SIZE = 0x9
};
