#pragma once

enum ERenderInputElement
{
	RENDER_INPUT_ELEMENT_POSITION = 0,
	RENDER_INPUT_ELEMENT_NORMAL = 1,
	RENDER_INPUT_ELEMENT_TANGENT = 2,
	RENDER_INPUT_ELEMENT_BINORMAL = 3,
	RENDER_INPUT_ELEMENT_BLENDWEIGHT = 4,
	RENDER_INPUT_ELEMENT_BLENDINDICES = 5,
	RENDER_INPUT_ELEMENT_TEXCOORD = 6,
	RENDER_INPUT_ELEMENT_COLOR = 7
};
