#pragma once

enum ERenderCompareFunc
{
	RENDER_COMPARISON_NEVER = 1,
	RENDER_COMPARISON_LESS = 2,
	RENDER_COMPARISON_EQUAL = 3,
	RENDER_COMPARISON_LESS_EQUAL = 4,
	RENDER_COMPARISON_GREATER = 5,
	RENDER_COMPARISON_NOT_EQUAL = 6,
	RENDER_COMPARISON_GREATER_EQUAL = 7,
	RENDER_COMPARISON_ALWAYS = 8
};
