#pragma once

enum ERenderPrimitiveTopology
{
	RENDER_PRIMITIVE_TOPOLOGY_INVALID = 0,
	RENDER_PRIMITIVE_TOPOLOGY_POINT_LIST = 1,
	RENDER_PRIMITIVE_TOPOLOGY_LINE_LIST = 2,
	RENDER_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
	RENDER_PRIMITIVE_TOPOLOGY_QUAD_LIST_EX = 4,
	RENDER_PRIMITIVE_TOPOLOGY_RECT_LIST_EX = 5,
	RENDER_PRIMITIVE_TOPOLOGY_PATCHLIST_3 = 6
};
