#pragma once

enum ERenderJobFlagShifts : __int32
{
    TYPE_SPRITES_SHIFT = 0x0,
    TYPE_SPAWNER_SHIFT = 0x1,
    WRAP_TILE_INDEX_SHIFT = 0x2,
    IGNORE_ROTATION_SHIFT = 0x3,
    SCREEN_ALIGNED_SHIFT = 0x4,
    SHARED_WS_FEEDBACK_SHIFT = 0x5
};
