#pragma once

enum ERenderResourceMipInterpolation : __int32
{
    eRENDER_RESOURCE_MIP_INTERPOLATION_NONE = 0x0,
    eRENDER_RESOURCE_MIP_INTERPOLATION_POINT = 0x1,
    eRENDER_RESOURCE_MIP_INTERPOLATION_LINEAR = 0x2,
    eRENDER_RESOURCE_MIP_INTERPOLATION_COUNT = 0x3
};
