#pragma once

enum ERenderPostfilterGlareType : __int32
{
    GLARE_TYPE_CAMERA = 0x0,
    GLARE_TYPE_NATURAL = 0x1,
    GLARE_TYPE_CHEAP_LENS = 0x2,
    GLARE_TYPE_FILTER_CROSS_SCREEN = 0x3,
    GLARE_TYPE_FILTER_CROSS_SCREEN_SPECTRAL = 0x4,
    GLARE_TYPE_FILTER_SNOW_CROSS = 0x5,
    GLARE_TYPE_FILTER_SNOW_CROSS_SPECTRAL = 0x6,
    GLARE_TYPE_FILTER_SUNNY_CROSS = 0x7,
    GLARE_TYPE_FILTER_SUNNY_CROSS_SPECTRAL = 0x8,
    GLARE_TYPE_CINECAM_VERTICAL_SLITS = 0x9,
    GLARE_TYPE_CINECAM_HORIZONTAL_SLITS = 0xA,
    GLARE_TYPE_USER_DEFINED = 0xB
};
