#pragma once

enum ERenderCompareFunc : __int32
{
    RENDER_COMPARISON_NEVER = 0x1,
    RENDER_COMPARISON_LESS = 0x2,
    RENDER_COMPARISON_EQUAL = 0x3,
    RENDER_COMPARISON_LESS_EQUAL = 0x4,
    RENDER_COMPARISON_GREATER = 0x5,
    RENDER_COMPARISON_NOT_EQUAL = 0x6,
    RENDER_COMPARISON_GREATER_EQUAL = 0x7,
    RENDER_COMPARISON_ALWAYS = 0x8
};
