#pragma once

enum ERenderGlowTypes
{
	ERENDERGLOWTYPE_NONE = 0,
	ERENDERGLOWTYPE_ENEMIES = 1,
	ERENDERGLOWTYPE_ALLIES = 2,
	ERENDERGLOWTYPE_ITEMS = 3,
	ERENDERGLOWTYPE_BACKGROUND = 4,
	ERENDERGLOWTYPE_CONTRACT_TARGET = 5,
	ERENDERGLOWTYPE_OBJECTIVES = 6,
	ERENDERGLOWTYPE_BREADCRUMB = 7,
	ERENDERGLOWTYPE_BACKGROUNDUNMASKED = 8,
	ERENDERGLOWTYPE_SIZE = 9
};
