#pragma once

enum ERenderResourceMapType
{
	RENDER_RESOURCE_MAP_NONE = 0,
	RENDER_RESOURCE_MAP_READ = 1,
	RENDER_RESOURCE_MAP_WRITE = 2,
	RENDER_RESOURCE_MAP_READ_WRITE = 3,
	RENDER_RESOURCE_MAP_WRITE_DISCARD = 4,
	RENDER_RESOURCE_MAP_WRITE_NO_OVERWRITE = 5
};
