#pragma once

enum ERenderPostfilterStarType
{
	STAR_TYPE_DISABLE = 0,
	STAR_TYPE_CROSS = 1,
	STAR_TYPE_CROSS_FILTER = 2,
	STAR_TYPE_SNOW_CROSS = 3,
	STAR_TYPE_VERTICAL = 4,
	STAR_TYPE_SUNNY_CROSS = 5,
	STAR_TYPE_USER_DEFINED = 6
};
