#pragma once

enum ERenderBlendMode
{
	RENDER_BLEND_ZERO = 1,
	RENDER_BLEND_ONE = 2,
	RENDER_BLEND_SRC_COLOR = 3,
	RENDER_BLEND_INV_SRC_COLOR = 4,
	RENDER_BLEND_SRC_ALPHA = 5,
	RENDER_BLEND_INV_SRC_ALPHA = 6,
	RENDER_BLEND_DEST_COLOR = 7,
	RENDER_BLEND_INV_DEST_COLOR = 8,
	RENDER_BLEND_DEST_ALPHA = 9,
	RENDER_BLEND_INV_DEST_ALPHA = 10,
	RENDER_BLEND_SRC_ALPHA_SAT = 11,
	RENDER_BLEND_FACTOR = 12,
	RENDER_BLEND_INV_FACTOR = 13,
	RENDER_BLEND_SRC1_COLOR = 14,
	RENDER_BLEND_INV_SRC1_COLOR = 15,
	RENDER_BLEND_SRC1_ALPHA = 16,
	RENDER_BLEND_INV_SRC1_ALPHA = 17
};
