#pragma once

enum ERenderResourceMapType : __int32
{
    RENDER_RESOURCE_MAP_NONE = 0x0,
    RENDER_RESOURCE_MAP_READ = 0x1,
    RENDER_RESOURCE_MAP_WRITE = 0x2,
    RENDER_RESOURCE_MAP_READ_WRITE = 0x3,
    RENDER_RESOURCE_MAP_WRITE_DISCARD = 0x4,
    RENDER_RESOURCE_MAP_WRITE_NO_OVERWRITE = 0x5
};
