#pragma once

enum ERenderResourceUsage : __int32
{
    RENDER_RESOURCE_USAGE_DEFAULT = 0x1,
    RENDER_RESOURCE_USAGE_IMMUTABLE = 0x2,
    RENDER_RESOURCE_USAGE_DYNAMIC = 0x3,
    RENDER_RESOURCE_USAGE_STAGING = 0x4
};
