#pragma once

enum ERenderBlendMode : __int32
{
    RENDER_BLEND_ZERO = 0x1,
    RENDER_BLEND_ONE = 0x2,
    RENDER_BLEND_SRC_COLOR = 0x3,
    RENDER_BLEND_INV_SRC_COLOR = 0x4,
    RENDER_BLEND_SRC_ALPHA = 0x5,
    RENDER_BLEND_INV_SRC_ALPHA = 0x6,
    RENDER_BLEND_DEST_COLOR = 0x7,
    RENDER_BLEND_INV_DEST_COLOR = 0x8,
    RENDER_BLEND_DEST_ALPHA = 0x9,
    RENDER_BLEND_INV_DEST_ALPHA = 0xA,
    RENDER_BLEND_SRC_ALPHA_SAT = 0xB,
    RENDER_BLEND_FACTOR = 0xC,
    RENDER_BLEND_INV_FACTOR = 0xD,
    RENDER_BLEND_SRC1_COLOR = 0xE,
    RENDER_BLEND_INV_SRC1_COLOR = 0xF,
    RENDER_BLEND_SRC1_ALPHA = 0x10,
    RENDER_BLEND_INV_SRC1_ALPHA = 0x11,
};
