#pragma once

enum EHandleState
{
    EHANDLESTATE_CONSTRUCTED = 0x0,
    EHANDLESTATE_PENDING = 0x1,
    EHANDLESTATE_PROCESSED = 0x2,
    EHANDLESTATE_RELEASED = 0x3,
    EHANDLESTATE_DESTROYED = 0x4
};
