#pragma once

enum ECommunicationBarState : __int32
{
    COMMUNICATION_BAR_NONE = 0x0,
    COMMUNICATION_BAR_CLEAR = 0x1,
    COMMUNICATION_BAR_SEARCHING = 0x2,
    COMMUNICATION_BAR_SUSPICIOUS = 0x3,
    COMMUNICATION_BAR_HUNTING = 0x4,
    COMMUNICATION_BAR_HOSTILE = 0x5,
    COMMUNICATION_BAR_BLOOD_FOUND = 0x6,
    COMMUNICATION_BAR_BODY_FOUND = 0x7,
    COMMUNICATION_BAR_GUARDS_ALERTED = 0x8,
    COMMUNICATION_BAR_BACKUP_ARRIVED = 0x9
};
