#pragma once

enum ECommunicationBarState
{
	COMMUNICATION_BAR_NONE = 0,
	COMMUNICATION_BAR_CLEAR = 1,
	COMMUNICATION_BAR_SEARCHING = 2,
	COMMUNICATION_BAR_SUSPICIOUS = 3,
	COMMUNICATION_BAR_HUNTING = 4,
	COMMUNICATION_BAR_HOSTILE = 5,
	COMMUNICATION_BAR_BLOOD_FOUND = 6,
	COMMUNICATION_BAR_BODY_FOUND = 7,
	COMMUNICATION_BAR_GUARDS_ALERTED = 8,
	COMMUNICATION_BAR_BACKUP_ARRIVED = 9
};
