#pragma once

enum EHUDFadeReason : __int32
{
    HUD_FADE_REASON_DIFFICULTY = 0x0,
    HUD_FADE_REASON_FADER = 0x1,
    HUD_FADE_REASON_TUTORIAL = 0x2,
    HUD_FADE_REASON_HINTMESSAGE = 0x3,
    HUD_FADE_REASON_CODE_GENERAL = 0x4,
    HUD_FADE_REASON_CUTSCENE = 0x5,
    HUD_FADE_REASON_NUM = 0x6
};
