#pragma once

enum EHUDIconType
{
	HUD_ICON_NONE = 0,
	HUD_ICON_ALARM_TIMER = 1,
	HUD_ICON_CLOSECOMBAT = 2,
	HUD_ICON_BREADCRUMB = 3,
	HUD_ICON_EXIT = 4,
	HUD_ICON_OBJECTIVE = 5,
	HUD_ICON_TARGET = 6,
	HUD_ICON_TUTORIAL_ARROW = 7
};
