#pragma once

enum EMeBarState
{
	ME_BAR_NONE = 0,
	ME_BAR_TRESPASSING = 1,
	ME_BAR_DEEPTRESPASSING = 2,
	ME_BAR_VISIBLY_ARMED = 3,
	ME_BAR_CHANGING_DISGUISE = 4,
	ME_BAR_DISGUISE_BLOWN = 5,
	ME_BAR_DISGUISE_SUSPICIOUS = 6,
	ME_BAR_NEAR_BODY = 7
};
