#pragma once

enum EPushNotificationType
{
	PUSH_NOTIFICATION_OBJECTIVE = 0,
	PUSH_NOTIFICATION_DISGUISE = 1,
	PUSH_NOTIFICATION_CONTRACT = 2,
	PUSH_NOTIFICATION_CHALLENGE = 3,
	PUSH_NOTIFICATION_RATING = 4,
	PUSH_NOTIFICATION_SPECIAL_RATING_UNLOCKED = 5,
	PUSH_NOTIFICATION_CONTRACT_PICKED_UP = 6,
	PUSH_NOTIFICATION_TECHNIQUE_UNLOCKED = 7,
	PUSH_NOTIFICATION_SCORE_COMPARISON = 8
};
