#pragma once

enum EPushNotificationType : __int32
{
    PUSH_NOTIFICATION_OBJECTIVE = 0x0,
    PUSH_NOTIFICATION_DISGUISE = 0x1,
    PUSH_NOTIFICATION_CONTRACT = 0x2,
    PUSH_NOTIFICATION_CHALLENGE = 0x3,
    PUSH_NOTIFICATION_RATING = 0x4,
    PUSH_NOTIFICATION_SPECIAL_RATING_UNLOCKED = 0x5,
    PUSH_NOTIFICATION_CONTRACT_PICKED_UP = 0x6,
    PUSH_NOTIFICATION_TECHNIQUE_UNLOCKED = 0x7,
    PUSH_NOTIFICATION_SCORE_COMPARISON = 0x8
};
