#pragma once

enum EScreenAnchor : __int32
{
    SCREEN_ANCHOR_TOP_LEFT = 0x0,
    SCREEN_ANCHOR_TOP_CENTER = 0x1,
    SCREEN_ANCHOR_TOP_RIGHT = 0x2,
    SCREEN_ANCHOR_MIDDLE_LEFT = 0x3,
    SCREEN_ANCHOR_MIDDLE_CENTER = 0x4,
    SCREEN_ANCHOR_MIDDLE_RIGHT = 0x5,
    SCREEN_ANCHOR_BOTTOM_LEFT = 0x6,
    SCREEN_ANCHOR_BOTTOM_CENTER = 0x7,
    SCREEN_ANCHOR_BOTTOM_RIGHT = 0x8
};
