#pragma once

enum EScreenAnchor
{
	SCREEN_ANCHOR_TOP_LEFT = 0,
	SCREEN_ANCHOR_TOP_CENTER = 1,
	SCREEN_ANCHOR_TOP_RIGHT = 2,
	SCREEN_ANCHOR_MIDDLE_LEFT = 3,
	SCREEN_ANCHOR_MIDDLE_CENTER = 4,
	SCREEN_ANCHOR_MIDDLE_RIGHT = 5,
	SCREEN_ANCHOR_BOTTOM_LEFT = 6,
	SCREEN_ANCHOR_BOTTOM_CENTER = 7,
	SCREEN_ANCHOR_BOTTOM_RIGHT = 8
};
