#pragma once

enum EDisplaySetting : __int32
{
    DS_RESWIDTH = 0x0,
    DS_RESHEIGHT = 0x1,
    DS_REFRESHRATE = 0x2,
    DS_FULLSCREEN = 0x3,
    DS_EXCLUSIVEFULLSCREEN = 0x4,
    DS_VSYNC = 0x5,
    DS_MONITOR = 0x6,
    DS_ADAPTER = 0x7,
    DS_ASPECTRATIO = 0x8,
    DS_CLIENTRECT_LEFT = 0x9,
    DS_CLIENTRECT_TOP = 0xA,
    DS_CLIENTRECT_WIDTH = 0xB,
    DS_CLIENTRECT_HEIGHT = 0xC,
    DS_STEREOSCOPIC = 0xD,
    DS_STEREO_DEPTH = 0xE,
    DS_STEREO_STRENGTH = 0xF,
    DS_MAXIMIZED = 0x10,
    DS_FOCUSLOSS = 0x11,
    DS_DISABLEGDICURSOR = 0x12,
    DS_GAMMA = 0x13,
    DS_MSAA = 0x14,
    DS_SIZE = 0x15
};
