#pragma once

#include "SGBufferUsingEffectParametersBase.h"
#include "SEffectParametersPrechainMergeParameters.h"

struct SEffectParametersPostfilter : SGBufferUsingEffectParametersBase
{
	enum
	{
		EPRECHAINMERGE_PASSES = 3
	};

	enum
	{
		SSGI_MAIN_PASS = 0,
		SSGI_HBLUR_PASS = 1,
		SSGI_VBLUR_PASS = 2,
		SSGI_BLEND_PASS = 3,
		SSGI_NUM_PASSES = 4
	};

	enum
	{
		CRYSTAL_SSAO_CALCBENTNORMAL_PASS = 0,
		CRYSTAL_SSAO_BILATERALHOR_PASS = 1,
		CRYSTAL_SSAO_BILATERALVERT_PASS = 2,
		CRYSTAL_SSAO_NORMALAPPLY_PASS = 3,
		CRYSTAL_SSAO_NUM_PASSES = 4
	};

	bool m_bIsInit;
	bool m_bRebind;
	ZRenderEffectTechnique* m_pTFog;
	ZRenderEffectTechnique* m_pTHDRSampleLum;
	ZRenderEffectTechnique* m_pTHDRStar;
	ZRenderEffectTechnique* m_pTHDRStarLast;
	ZRenderEffectTechnique* m_pTHDRBloomLast;
	ZRenderEffectTechnique* m_pTHDRBloomVignette;
	ZRenderEffectTechnique* m_pTHDRTonemapAndBrightPass;
	ZRenderEffectTechnique* m_pTMergeUp;
	ZRenderEffectTechnique* m_pTMergeUpNoBlur;
	ZRenderEffectTechnique* m_pTMotionBlur;
	ZRenderEffectTechnique* m_pTRadialVolumeLight;
	ZRenderEffectTechnique* m_pTRadialBlur;
	ZRenderEffectTechnique* m_pTRadialTint;
	ZRenderEffectTechnique* m_pTVideoEffects;
	ZRenderEffectTechnique* m_pTDeferredTransResolveLiquid;
	ZRenderEffectTechnique* m_pTScreenDecals;
	ZRenderEffectTechnique* m_pTDepthOfField;
	ZRenderEffectTechnique* m_pTPreChainMerge;
	ZRenderEffectTechnique* m_pTPreChainMerge_CCFAR;
	ZRenderEffectTechnique* m_pTPostChainMerge;
	ZRenderEffectTechnique* m_pTGammaCorrection;
	ZRenderEffectTechnique* m_pTNEW_SSAO;
	SEffectParametersPrechainMergeParameters m_PrechainMergeParameters[3];
	SEffectParametersPrechainMergeParameters m_PrechainMergeParameters_CCFAR[3];
	ZRenderShader* m_pPrechainMergeShaderV;
	ZRenderShader* m_pGammaCorrection_PS;
	unsigned long long m_GammaCorrectionParamsPS;
	ZRenderShader* m_pHDRDownSampleAndTonemapPS;
	unsigned long long m_TonemapScale_HDRDownSampleAndTonemapPS;
	unsigned int m_STLC1_HDRDownSampleAndTonemapPS;
	unsigned int m_STLC2_HDRDownSampleAndTonemapPS;
	ZRenderShader* m_pHDRDownSampleAndTonemapNoDofPS;
	unsigned int m_STLC1_HDRDownSampleAndTonemapNoDofPS;
	ZRenderShader* m_pHDRTonemapPS;
	unsigned long long m_SampleOffsets_HDRTonemapPS;
	unsigned long long m_BrightPassThreshold_HDRTonemapPS;
	unsigned long long m_GlareSaturation_HDRTonemapPS;
	unsigned long long m_TonemapScale_HDRTonemapPS;
	unsigned int m_STLC1_HDRTonemapPS;
	unsigned int m_STLC0_HDRTonemapPS;
	ZRenderShader* m_pHDRTonemapNoDofPS;
	unsigned long long m_BrightPassThreshold_HDRTonemapNoDofPS;
	unsigned long long m_GlareSaturation_HDRTonemapNoDofPS;
	unsigned long long m_TonemapScale_HDRTonemapNoDofPS;
	unsigned int m_STLC0_HDRTonemapNoDofPS;
	ZRenderShader* m_HDRSampleLumInitialVS;
	unsigned long long m_SampleOffsets_HDRSampleLumInitialVS;
	ZRenderShader* m_HDRSampleLumInitialPS;
	ZRenderShader* m_HDRSampleLumIterativePS;
	unsigned long long m_SampleOffsets_HDRSampleLumIterativePS;
	ZRenderShader* m_HDRSampleLumFinalPS;
	unsigned long long m_SampleOffsets_HDRSampleLumFinalPS;
	ZRenderShader* m_DepthOfField_DownSampleDepthCoC_PS;
	unsigned long long m_Params0_DepthOfField_DownSampleDepthCoC_PS;
	unsigned long long m_Params1_DepthOfField_DownSampleDepthCoC_PS;
	unsigned long long m_Params2_DepthOfField_DownSampleDepthCoC_PS;
	ZRenderShader* m_DepthOfField_DownSampleDepthCoC2x2To4x4_PS;
	ZRenderShader* m_BlurSep5_WCoC_VS;
	unsigned long long m_Params0_BlurSep5_WCoC_VS;
	ZRenderShader* m_BlurSep5_WCoC_PS;
	ZRenderShader* m_DepthOfField_BlurLinearDepth_PS;
	ZRenderShader* m_DepthOfField_DebugShowCoC_PS;
	unsigned long long m_Params0_DepthOfField_DebugShowCoC_PS;
	unsigned long long m_Params1_DepthOfField_DebugShowCoC_PS;
	unsigned long long m_Params2_DepthOfField_DebugShowCoC_PS;
	unsigned int m_STPC0_DepthOfField_DebugShowCoC_PS;
	unsigned int m_STPC1_DepthOfField_DebugShowCoC_PS;
	ZRenderShader* m_BlurSpawn_PS;
	unsigned int m_STLC0_m_BlurSpawn_PS;
	ZRenderShader* m_BlurSpawnSoft_PS;
	unsigned int m_STLC0_m_BlurSpawnSoft_PS;
	ZRenderShader* m_LensBlurHQ_WCoC_VS;
	ZRenderShader* m_BlurLensBlur_WCoC_PS;
	unsigned long long m_Params0_LensBlurHQ_WCoC_VS;
	ZRenderShader* m_1PassBlur_WCoC_PS;
	ZRenderShader* m_LensBlur_WCoC_VS;
	unsigned long long m_Params0_LensBlur_WCoC_VS;
	ZRenderShader* m_LensBlur_WCoC_PS;
	unsigned int m_STLC0_LensBlur_WCoC_PS;
	ZRenderShader* m_MaxBlend_FgCoC_PS;
	unsigned long long m_MaxBlend_FgCoC_PS_OverlapStrength;
	ZRenderShader* m_HDRBloomVignette_PS;
	unsigned long long m_LensFlareAttenuation_HDRBloomVignette_PS;
	ZRenderShader* m_HDRBloomLast_PS;
	unsigned long long m_BloomScale_HDRBloomLast_PS;
	unsigned long long m_LensFlareColorA_HDRBloomLast_PS;
	unsigned long long m_LensFlareColorB_HDRBloomLast_PS;
	unsigned long long m_LensFlareColorC_HDRBloomLast_PS;
	unsigned long long m_LensFlareColorD_HDRBloomLast_PS;
	unsigned long long m_LensFlareThresholds_HDRBloomLast_PS;
	unsigned int m_STLB0_HDRBloomLast_PS;
	unsigned int m_STLB2_HDRBloomLast_PS;
	ZRenderShader* m_HDRStar_VS;
	unsigned long long m_SampleOffsets_HDRStar_VS;
	ZRenderShader* m_HDRStar_PS;
	unsigned long long m_SampleWeights_HDRStar_PS;
	ZRenderShader* m_HDRStarLast_PS;
	unsigned long long m_SampleWeights_HDRStarLast_PS;
	unsigned long long m_StarScale_HDRStarLast_PS;
	unsigned int m_STLB0_HDRStarLast_PS;
	unsigned int m_STLB1_HDRStarLast_PS;
	ZRenderShader* m_MotionBlur_PS;
	unsigned long long m_Blurriness_MotionBlur_PS;
	unsigned long long m_EyeUpperLeft_MotionBlur_PS;
	unsigned long long m_EyeLowerRight_MotionBlur_PS;
	unsigned long long m_Matrix0_MotionBlur_PS;
	unsigned long long m_Matrix1_MotionBlur_PS;
	unsigned long long m_Matrix2_MotionBlur_PS;
	unsigned int m_STPC0_MotionBlur_PS;
	unsigned int m_STLC0_MotionBlur_PS;
	ZRenderShader* m_PerVertexEyeVector_VS;
	unsigned long long m_pEyeUpperLeft_PerVertexEyeVector_VS;
	unsigned long long m_pEyeUpperRight_PerVertexEyeVector_VS;
	unsigned long long m_pEyeLowerLeft_PerVertexEyeVector_VS;
	unsigned long long m_pEyeLowerRight_PerVertexEyeVector_VS;
	ZRenderShader* m_Fog_VS;
	unsigned long long m_pEyeUpperLeft_Fog_VS;
	unsigned long long m_pEyeUpperRight_Fog_VS;
	unsigned long long m_pEyeLowerLeft_Fog_VS;
	unsigned long long m_pEyeLowerRight_Fog_VS;
	unsigned long long m_FogDensity_Fog_VS;
	unsigned long long m_TurbulenceScale_Fog_VS;
	ZRenderShader* m_Fog_PS[9];
	unsigned long long m_ViewRemap_Fog_PS[9];
	unsigned long long m_CameraPosition_Fog_PS[9];
	unsigned long long m_FogNearDistance_Fog_PS[9];
	unsigned long long m_TurbulenceSampleWeights_Fog_PS[9];
	unsigned long long m_TurbulenceOctaveOffset_Fog_PS[9];
	unsigned long long m_TurbulenceOpacity_Fog_PS[9];
	unsigned long long m_FadeParams_Fog_PS[9];
	unsigned long long m_FadeParams2_Fog_PS[9];
	unsigned int m_STPC0_Fog_PS[9];
	unsigned int m_SVLW2_Fog_PS[9];
	ZRenderShader* m_FogResolve_VS;
	unsigned long long m_FogTargetSize_FogResolve_VS;
	ZRenderShader* m_FogResolve_PS[1];
	unsigned long long m_ViewRemap_FogResolve_PS[1];
	unsigned long long m_FogColor_FogResolve_PS[1];
	unsigned long long m_FogPixelSize_FogResolve_PS[1];
	unsigned long long m_FogPixelOffsets_FogResolve_PS[1];
	unsigned int m_STPC0_FogResolve_PS[1];
	unsigned int m_STPC1_FogResolve_PS[1];
	unsigned int m_STPC2_FogResolve_PS[1];
	ZRenderShader* m_DOFRegionFinalPass_PS;
	unsigned long long m_ViewRemap_DOFRegionFinalPass_PS;
	unsigned long long m_CameraPosition_DOFRegionFinalPass_PS;
	unsigned long long m_RegionCenter_DOFRegionFinalPass_PS;
	unsigned long long m_FocalRange_DOFRegionFinalPass_PS;
	unsigned long long m_FocalFade_DOFRegionFinalPass_PS;
	unsigned long long m_Blurriness_DOFRegionFinalPass_PS;
	unsigned int m_STPC0_DOFRegionFinalPass_PS;
	unsigned int m_STPC1_DOFRegionFinalPass_PS;
	unsigned int m_STLC2_DOFRegionFinalPass_PS;
	ZRenderShader* m_MergeUp_PS;
	unsigned long long m_SampleOffsets_MergeUp_PS;
	unsigned long long m_SampleWeights_MergeUp_PS;
	unsigned long long m_Blurriness_MergeUp_PS;
	unsigned int m_STLC0_MergeUp_PS;
	unsigned int m_STLC1_MergeUp_PS;
	ZRenderShader* m_MergeUpNoBlur_PS;
	unsigned long long m_Blurriness_MergeUpNoBlur_PS;
	unsigned int m_STLC0_MergeUpNoBlur_PS;
	unsigned int m_STLC1_MergeUpNoBlur_PS;
	ZRenderShader* m_RadialBlur_PS;
	unsigned long long m_RadialParams_RadialBlur_PS;
	unsigned long long m_Blurriness_RadialBlur_PS;
	unsigned long long m_RadialCenter_RadialBlur_PS;
	unsigned long long m_ScreenAspectXByY_RadialBlur_PS;
	ZRenderShader* m_RadialTint_PS;
	unsigned long long m_RadialParams_RadialTint_PS;
	unsigned long long m_Blurriness_RadialTint_PS;
	unsigned long long m_RadialCenter_RadialTint_PS;
	unsigned long long m_ScreenAspectXByY_RadialTint_PS;
	unsigned int m_STLC0_RadialTint_PS;
	unsigned int m_STLC1_RadialTint_PS;
	ZRenderShader* m_DistortWobble_PS;
	unsigned long long m_DistortionScale_DistortWobble_PS;
	unsigned long long m_DistortWobbleTime_DistortWobble_PS;
	unsigned long long m_DistortWobbleWaveLength_DistortWobble_PS;
	ZRenderShader* m_VideoEffects_PS;
	unsigned long long m_VideoScale_VideoEffects_PS;
	unsigned long long m_VideoOffset_VideoEffects_PS;
	unsigned long long m_VideoHorizSkew_VideoEffects_PS;
	unsigned long long m_VideoHorizBend_VideoEffects_PS;
	unsigned long long m_VideoFineShaking_VideoEffects_PS;
	unsigned long long m_VideoColorNoise_VideoEffects_PS;
	unsigned int m_STLW0_VideoEffects_PS;
	unsigned int m_STLW1_VideoEffects_PS;
	ZRenderShader* m_PostChainMerge_VS;
	unsigned long long m_Size_PostChainMerge_VS;
	unsigned long long m_Offset_PostChainMerge_VS;
	unsigned long long m_VignetteParams_PostChainMerge_VS;
	unsigned long long m_Params2_PostChainMerge_VS;
	unsigned long long m_Params3_PostChainMerge_VS;
	unsigned long long m_Params4_PostChainMerge_VS;
	unsigned long long m_Barrel_PostChainMerge_VS;
	ZRenderShader* m_PostChainMerge_PS;
	unsigned long long m_NoiseIntensity_PostChainMerge_PS;
	unsigned int m_TLC0_PostChainMerge_PS;
	unsigned int m_TLC2_PostChainMerge_PS;
	unsigned int m_TLW1_PostChainMerge_PS;
	ZRenderShader* m_PostChainMergeSD_PS;
	unsigned long long m_NoiseIntensity_PostChainMergeSD_PS;
	unsigned long long m_Gamma_PostChainMergeSD_PS;
	unsigned long long m_Params0_PostChainMergeSD_PS;
	unsigned long long m_Params1_PostChainMergeSD_PS;
	unsigned int m_TLC0_PostChainMergeSD_PS;
	unsigned int m_TLC1_PostChainMergeSD_PS;
	unsigned int m_TLC2_PostChainMergeSD_PS;
	unsigned int m_TLB0_PostChainMergeSD_PS;
	unsigned int m_TLW1_PostChainMergeSD_PS;
	ZRenderShader* m_ScreenDecals_VS;
	unsigned long long m_vParams0_ScreenDecals_VS;
	unsigned long long m_vParams1_ScreenDecals_VS;
	unsigned long long m_vParams2_ScreenDecals_VS;
	ZRenderShader* m_ScreenDecals_PS;
	unsigned long long m_vParams3_ScreenDecals_PS;
	ZRenderShader* m_NEW_SSAO_DownScale_PS;
	unsigned long long m_ViewRemap_NEW_SSAO_DownScale_PS;
	unsigned long long m_SSAO_FarDistance_NEW_SSAO_DownScale_PS;
	unsigned long long m_Params1_NEW_SSAO_DownScale_PS;
	unsigned long long m_Params2_NEW_SSAO_DownScale_PS;
	unsigned int m_Deferred0_NEW_SSAO_DownScale_PS;
	unsigned int m_Deferred1_NEW_SSAO_DownScale_PS;
	ZRenderShader* m_NEW_SSAO_DownScaleNoDof_PS;
	unsigned long long m_ViewRemap_NEW_SSAO_DownScaleNoDof_PS;
	unsigned long long m_SSAO_FarDistance_NEW_SSAO_DownScaleNoDof_PS;
	unsigned int m_Deferred0_NEW_SSAO_DownScaleNoDof_PS;
	unsigned int m_Deferred1_NEW_SSAO_DownScaleNoDof_PS;
	ZRenderShader* m_OLE_SSAO_VS;
	unsigned long long m_SSAO_RandScale_OLE_SSAO_VS;
	ZRenderShader* m_OLE_SSAO_PS;
	unsigned long long m_SSAO_SampleRadii_OLE_SSAO_PS;
	unsigned long long m_SSAO_FarDistance_OLE_SSAO_PS;
	unsigned long long m_SSAO_NearFadeParams_OLE_SSAO_PS;
	unsigned long long m_SSAO_Params_OLE_SSAO_PS;
	unsigned long long m_SSAO_Color_OLE_SSAO_PS;
	unsigned long long m_ScaledEyeUpperLeft_OLE_SSAO_PS;
	unsigned long long m_ScaledEyeDelta_OLE_SSAO_PS;
	unsigned int m_STPC0_OLE_SSAO_PS;
	unsigned int m_RandBases_OLE_SSAO_PS;
	ZRenderShader* m_HBAO_PS;
	ZRenderTexture2D* m_HBAO_Random;
	ZRenderShaderResourceView* m_HBAO_RandomSRV;
	unsigned long long m_HBAO_1;
	unsigned long long m_HBAO_2;
	unsigned long long m_HBAO_3;
	unsigned int m_HBAO_Random_PS;
	unsigned int m_HBAO_Depth_PS;
	ZRenderShader* m_SSGI_PS[4];
	unsigned long long m_SSGI_MAIN_Params0_PS;
	unsigned int m_SSGI_MAIN_TLC0_PS;
	unsigned int m_SSGI_MAIN_TLC1_PS;
	unsigned int m_SSGI_MAIN_TLC2_PS;
	unsigned int m_SSGI_MAIN_TLW3_PS;
	unsigned long long m_SSGI_HBLUR_Params0_PS;
	unsigned int m_SSGI_HBLUR_TLC0_PS;
	unsigned long long m_SSGI_VBLUR_Params0_PS;
	unsigned int m_SSGI_VBLUR_TLC0_PS;
	unsigned int m_SSGI_BLEND_TPC0_PS;
	unsigned int m_SSGI_BLEND_TLC1_PS;
	unsigned int m_SSGI_BLEND_TPC2_PS;
	ZRenderShader* m_RadialVolumeLight_PS;
	unsigned long long m_ScreenAspectXByY_RVL_PS;
	unsigned long long m_RadialCenter_RVL_PS;
	ZRenderShader* m_RadialVolumeLight_Blur1_PS;
	unsigned long long m_SampleWeights_RadialVolumeLight_Blur1_PS;
	unsigned long long m_VolumeLightParameters_RVLBLUR1_PS;
	unsigned long long m_RadialCenter_RVLBLUR1_PS;
	unsigned int m_STLPC0_RVLBLUR1_PS;
	ZRenderShader* m_RadialVolumeLight_Blur2_PS;
	unsigned long long m_SampleWeights_RadialVolumeLight_Blur2_PS;
	unsigned long long m_VolumeLightParameters_RVLBLUR2_PS;
	unsigned long long m_RadialCenter_RVLBLUR2_PS;
	unsigned int m_STLPC0_RVLBLUR2_PS;
	ZRenderShader* m_RadialVolumeLight_Blur2Merge_PS;
	unsigned long long m_SampleWeights_RadialVolumeLight_Blur2Merge_PS;
	unsigned long long m_VolumeLightParameters_RVLBLUR2Merge_PS;
	unsigned long long m_RadialCenter_RVLBLUR2Merge_PS;
	unsigned long long m_ApplyTint_RadialVolumeLight_Blur2Merge_PS;
	unsigned int m_STLPC0_RVLBLUR2Merge_PS;
	ZRenderShader* m_RadialVolumeLight_Apply_PS;
	unsigned long long m_VParams_RVLAPPLY_PS;
	unsigned int m_STLPC0_RVLAPPLY_PS;
	ZRenderShader* m_DoubleVision_PS;
	unsigned long long m_DV1_DoubleVision_PS;
	unsigned long long m_DV2_DoubleVision_PS;
	unsigned long long m_DVB_DoubleVision_PS;
	unsigned int m_TLC0_DoubleVision_PS;
	ZRenderShader* m_CrystalSSAO_PS[4];
	unsigned long long m_CrystalSSAO_CALCBENTNORMAL_Params0_PS;
	unsigned long long m_CrystalSSAO_CALCBENTNORMAL_Params1_PS;
	unsigned long long m_CrystalSSAO_CALCBENTNORMAL_Params2_PS;
	unsigned int m_CrystalSSAO_CALCBENTNORMAL_TPC0_PS;
	unsigned int m_CrystalSSAO_CALCBENTNORMAL_TPW1_PS;
	unsigned int m_CrystalSSAO_CALCBENTNORMAL_TPC2_PS;
	unsigned int m_CrystalSSAO_CALCBENTNORMAL_TPC3_PS;
	unsigned long long m_CrystalSSAO_BILATERALHOR_Params0_PS;
	unsigned long long m_CrystalSSAO_BILATERALHOR_Params1_PS;
	unsigned int m_CrystalSSAO_BILATERALHOR_TPC0_PS;
	unsigned int m_CrystalSSAO_BILATERALHOR_TPC1_PS;
	unsigned long long m_CrystalSSAO_BILATERALVERT_Params0_PS;
	unsigned long long m_CrystalSSAO_BILATERALVERT_Params1_PS;
	unsigned int m_CrystalSSAO_BILATERALVERT_TPC0_PS;
	unsigned int m_CrystalSSAO_BILATERALVERT_TPC1_PS;
	unsigned long long m_CrystalSSAO_NORMALAPPLY_Params0_PS;
	unsigned long long m_CrystalSSAO_NORMALAPPLY_Params1_PS;
	unsigned long long m_CrystalSSAO_NORMALAPPLY_Params2_PS;
	unsigned int m_CrystalSSAO_NORMALAPPLY_TPC0_PS;
	unsigned int m_CrystalSSAO_NORMALAPPLY_TPC1_PS;
	unsigned int m_CrystalSSAO_NORMALAPPLY_TPC2_PS;
	unsigned int m_CrystalSSAO_NORMALAPPLY_TPC3_PS;
	unsigned int m_CrystalSSAO_NORMALAPPLY_TPC4_PS;
	ZRenderShader* m_GateDepth_PS;
	ZRenderShader* m_GateDepth_VS;
	ZRenderShader* m_GateDepthBoxFade_PS;
	ZRenderShader* m_GateDepthBoxFade_VS;
	SEffectResourceLoader m_EffectLoader;

	~SEffectParametersPostfilter() override = default;
	void Update(ZRenderEffect* pEffect) override;

	SEffectParametersPostfilter() = default;
	void Update(int nMsaa);
	void Init(unsigned int nMsaa);
	void RebindEffectResource();
};
