#pragma once

#include "SGBufferUsingEffectParametersBase.h"

struct SEffectParametersGlobalIllumination : SGBufferUsingEffectParametersBase
{
	ZRenderShader* m_pInjectLight_VS;
	ZRenderShader* m_pInjectLight_GS;
	ZRenderShader* m_pInjectLight_PS;
	ZRenderShader* m_pPropagateLPV_VS;
	ZRenderShader* m_pPropagateLPV_GS;
	ZRenderShader* m_pPropagateLPV_PS;
	ZRenderShader* m_pDrawLight_PS;
	ZRenderShader* m_pDrawLightMsaa2_PS;
	ZRenderShader* m_pDrawLightMsaa4_PS;
	ZRenderShader* m_pDrawLightMsaa8_PS;
	ZRenderShader* m_pDrawLightMsaa21_PS;
	ZRenderShader* m_pDrawLightMsaa41_PS;
	ZRenderShader* m_pDrawLightMsaa81_PS;
	unsigned long long m_Injection_Params0_VS;
	unsigned long long m_Injection_LightProjToView_VS;
	unsigned long long m_Injection_LightViewToLPV_VS;
	unsigned long long m_Injection_LightViewToWorld_VS;
	unsigned long long m_Injection_LPVDimension_VS;
	unsigned long long m_Injection_LPVDimension_GS;
	unsigned long long m_Propagate_Params0_PS;
	unsigned long long m_Propagate_LPVDimension_PS;
	unsigned int m_GI_INJECTLIGHT_RSM_DEPTH_VS;
	unsigned int m_GI_INJECTLIGHT_RSM_NORMAL_VS;
	unsigned int m_GI_INJECTLIGHT_RSM_DIFFUSE_VS;
	unsigned int m_GI_PROPAGATE_LPV_RED_PS;
	unsigned int m_GI_PROPAGATE_LPV_GREEN_PS;
	unsigned int m_GI_PROPAGATE_LPV_BLUE_PS;
	unsigned int m_DrawLight_Texture_GBuffer1;
	unsigned int m_DrawLight_Texture_GBuffer2;
	unsigned int m_DrawLight_Texture_Depth;
	unsigned int m_DrawLight_Texture_LPV_Red;
	unsigned int m_DrawLight_Texture_LPV_Green;
	unsigned int m_DrawLight_Texture_LPV_Blue;
	unsigned long long m_DrawLight_Constant_InverseProjection;
	unsigned long long m_DrawLight_Constant_ViewToLPV;
	unsigned long long m_DrawLight_Constant_BackBufferSize;
	unsigned long long m_DrawLight_Constant_LPVDimension;
	unsigned long long m_DrawLight_Constant_Params1;
	unsigned int m_DrawLight_Texture_GBuffer1Msaa2;
	unsigned int m_DrawLight_Texture_GBuffer2Msaa2;
	unsigned int m_DrawLight_Texture_DepthMsaa2;
	unsigned int m_DrawLight_Texture_LPV_RedMsaa2;
	unsigned int m_DrawLight_Texture_LPV_GreenMsaa2;
	unsigned int m_DrawLight_Texture_LPV_BlueMsaa2;
	unsigned long long m_DrawLight_Constant_InverseProjectionMsaa2;
	unsigned long long m_DrawLight_Constant_ViewToLPVMsaa2;
	unsigned long long m_DrawLight_Constant_BackBufferSizeMsaa2;
	unsigned long long m_DrawLight_Constant_LPVDimensionMsaa2;
	unsigned long long m_DrawLight_Constant_Params1Msaa2;
	unsigned int m_DrawLight_Texture_GBuffer1Msaa4;
	unsigned int m_DrawLight_Texture_GBuffer2Msaa4;
	unsigned int m_DrawLight_Texture_DepthMsaa4;
	unsigned int m_DrawLight_Texture_LPV_RedMsaa4;
	unsigned int m_DrawLight_Texture_LPV_GreenMsaa4;
	unsigned int m_DrawLight_Texture_LPV_BlueMsaa4;
	unsigned long long m_DrawLight_Constant_InverseProjectionMsaa4;
	unsigned long long m_DrawLight_Constant_ViewToLPVMsaa4;
	unsigned long long m_DrawLight_Constant_BackBufferSizeMsaa4;
	unsigned long long m_DrawLight_Constant_LPVDimensionMsaa4;
	unsigned long long m_DrawLight_Constant_Params1Msaa4;
	unsigned int m_DrawLight_Texture_GBuffer1Msaa8;
	unsigned int m_DrawLight_Texture_GBuffer2Msaa8;
	unsigned int m_DrawLight_Texture_DepthMsaa8;
	unsigned int m_DrawLight_Texture_LPV_RedMsaa8;
	unsigned int m_DrawLight_Texture_LPV_GreenMsaa8;
	unsigned int m_DrawLight_Texture_LPV_BlueMsaa8;
	unsigned long long m_DrawLight_Constant_InverseProjectionMsaa8;
	unsigned long long m_DrawLight_Constant_ViewToLPVMsaa8;
	unsigned long long m_DrawLight_Constant_BackBufferSizeMsaa8;
	unsigned long long m_DrawLight_Constant_LPVDimensionMsaa8;
	unsigned long long m_DrawLight_Constant_Params1Msaa8;
	unsigned int m_DrawLight_Texture_GBuffer1Msaa2_1;
	unsigned int m_DrawLight_Texture_GBuffer2Msaa2_1;
	unsigned int m_DrawLight_Texture_DepthMsaa2_1;
	unsigned int m_DrawLight_Texture_LPV_RedMsaa2_1;
	unsigned int m_DrawLight_Texture_LPV_GreenMsaa2_1;
	unsigned int m_DrawLight_Texture_LPV_BlueMsaa2_1;
	unsigned long long m_DrawLight_Constant_InverseProjectionMsaa2_1;
	unsigned long long m_DrawLight_Constant_ViewToLPVMsaa2_1;
	unsigned long long m_DrawLight_Constant_BackBufferSizeMsaa2_1;
	unsigned long long m_DrawLight_Constant_LPVDimensionMsaa2_1;
	unsigned long long m_DrawLight_Constant_Params1Msaa2_1;
	unsigned int m_DrawLight_Texture_GBuffer1Msaa4_1;
	unsigned int m_DrawLight_Texture_GBuffer2Msaa4_1;
	unsigned int m_DrawLight_Texture_DepthMsaa4_1;
	unsigned int m_DrawLight_Texture_LPV_RedMsaa4_1;
	unsigned int m_DrawLight_Texture_LPV_GreenMsaa4_1;
	unsigned int m_DrawLight_Texture_LPV_BlueMsaa4_1;
	unsigned long long m_DrawLight_Constant_InverseProjectionMsaa4_1;
	unsigned long long m_DrawLight_Constant_ViewToLPVMsaa4_1;
	unsigned long long m_DrawLight_Constant_BackBufferSizeMsaa4_1;
	unsigned long long m_DrawLight_Constant_LPVDimensionMsaa4_1;
	unsigned long long m_DrawLight_Constant_Params1Msaa4_1;
	unsigned int m_DrawLight_Texture_GBuffer1Msaa8_1;
	unsigned int m_DrawLight_Texture_GBuffer2Msaa8_1;
	unsigned int m_DrawLight_Texture_DepthMsaa8_1;
	unsigned int m_DrawLight_Texture_LPV_RedMsaa8_1;
	unsigned int m_DrawLight_Texture_LPV_GreenMsaa8_1;
	unsigned int m_DrawLight_Texture_LPV_BlueMsaa8_1;
	unsigned long long m_DrawLight_Constant_InverseProjectionMsaa8_1;
	unsigned long long m_DrawLight_Constant_ViewToLPVMsaa8_1;
	unsigned long long m_DrawLight_Constant_BackBufferSizeMsaa8_1;
	unsigned long long m_DrawLight_Constant_LPVDimensionMsaa8_1;
	unsigned long long m_DrawLight_Constant_Params1Msaa8_1;
	ZRenderInputLayout* m_pPropagateInputLayout;
	SEffectResourceLoader m_EffectLoader;

	~SEffectParametersGlobalIllumination() override = default;
	void Update(ZRenderEffect* pEffect) override;

	SEffectParametersGlobalIllumination() = default;
	void Init();
	void RebindEffectResource();
};
