#pragma once

enum CrowdRegionType : __int32
{
    CROWDSPHERE_NONE = 0x0,
    CROWDSPHERE_POI = 0x1,
    CROWDSPHERE_AVOID = 0x2,
    CROWDSPHERE_STOP = 0x3,
    CROWDSPHERE_ALERT = 0x4,
    CROWDSPHERE_SCARE = 0x5,
    CROWDSPHERE_GETDOWN = 0x6
};
