#pragma once

enum CrowdRegionType
{
	CROWDSPHERE_NONE = 0,
	CROWDSPHERE_POI = 1,
	CROWDSPHERE_AVOID = 2,
	CROWDSPHERE_STOP = 3,
	CROWDSPHERE_ALERT = 4,
	CROWDSPHERE_SCARE = 5,
	CROWDSPHERE_GETDOWN = 6
};
