#pragma once

namespace CrowdMapImpl
{
	enum CellFlags
	{
		CELLFLAG_RESTRICTED_A = 1,
		CELLFLAG_RESTRICTED_B = 2,
		CELLFLAG_RESTRICTED_C = 4,
		CELLFLAG_WALKABLE = 8,
		CELLFLAG_TELEPORT_IN = 16,
		CELLFLAG_TELEPORT_OUT = 32,
		CELLFLAG_GROUP = 64,
		CELLFLAG_PANIC_ONLY = 128
	};
}
