#pragma once

enum EPhysicsObjectType : __int32
{
    EPHYSICSOBJECTTYPE_UNKNOWN = 0x0,
    EPHYSICSOBJECTTYPE_DYNAMIC = 0x1,
    EPHYSICSOBJECTTYPE_KINEMATIC = 0x2,
    EPHYSICSOBJECTTYPE_STATIC = 0x3
};
