#pragma once

enum EHM5SoundFootwearType : __int32
{
    EFWT_UNDEFINED = 0x0,
    EFWT_BAREFOOT = 0x1,
    EFWT_SLIPPERS = 0x2,
    EFWT_DISPOSABLE_SLIPPERS = 0x3,
    EFWT_SANDALS = 0x4,
    EFWT_SNEAKERS = 0x5,
    EFWT_SNEAKERS_METALLEG = 0x6,
    EFWT_LEATHER = 0x7,
    EFWT_FEMALE_LEATHER = 0x8,
    EFWT_BOOTS = 0x9,
    EFWT_COWBOY_BOOTS = 0xA,
    EFWT_FEMALE_COWBOY_BOOTS = 0xB,
    EFWT_RUBBER_BOOTS = 0xC,
    EFWT_HIGH_HEELS = 0xD,
    EFWT_LEATHER_KEYS = 0xE,
    EFWT_SWAT_BOOTS = 0xF,
    EFWT_NUMFOOTWEARTYPES = 0x10
};
