#pragma once

enum EHM5SoundFootwearType
{
	EFWT_UNDEFINED = 0,
	EFWT_BAREFOOT = 1,
	EFWT_SLIPPERS = 2,
	EFWT_DISPOSABLE_SLIPPERS = 3,
	EFWT_SANDALS = 4,
	EFWT_SNEAKERS = 5,
	EFWT_SNEAKERS_METALLEG = 6,
	EFWT_LEATHER = 7,
	EFWT_FEMALE_LEATHER = 8,
	EFWT_BOOTS = 9,
	EFWT_COWBOY_BOOTS = 10,
	EFWT_FEMALE_COWBOY_BOOTS = 11,
	EFWT_RUBBER_BOOTS = 12,
	EFWT_HIGH_HEELS = 13,
	EFWT_LEATHER_KEYS = 14,
	EFWT_SWAT_BOOTS = 15,
	EFWT_NUMFOOTWEARTYPES = 16
};
