#pragma once

enum FMOD_CHANNEL_CALLBACKTYPE
{
	FMOD_CHANNEL_CALLBACKTYPE_END = 0,
	FMOD_CHANNEL_CALLBACKTYPE_VIRTUALVOICE = 1,
	FMOD_CHANNEL_CALLBACKTYPE_SYNCPOINT = 2,
	FMOD_CHANNEL_CALLBACKTYPE_OCCLUSION = 3,
	FMOD_CHANNEL_CALLBACKTYPE_MAX = 4,
	FMOD_CHANNEL_CALLBACKTYPE_FORCEINT = 65536
};
