#pragma once

enum FMOD_CHANNEL_CALLBACKTYPE
{
    FMOD_CHANNEL_CALLBACKTYPE_END = 0x0,
    FMOD_CHANNEL_CALLBACKTYPE_VIRTUALVOICE = 0x1,
    FMOD_CHANNEL_CALLBACKTYPE_SYNCPOINT = 0x2,
    FMOD_CHANNEL_CALLBACKTYPE_OCCLUSION = 0x3,
    FMOD_CHANNEL_CALLBACKTYPE_MAX = 0x4,
    FMOD_CHANNEL_CALLBACKTYPE_FORCEINT = 0x10000
};
