#pragma once

enum EBaseMovementType : unsigned __int32
{
    eMovementNone = 0xFFFFFFFF,
    eMovementDead = 0x0,
    eMovementLedgeHang = 0x1,
    eMovementLedgeWalk = 0x2,
    eMovementClimbWindow = 0x3,
    eMovementShootingBallet = 0x4,
    eMovementCover = 0x5,
    eMovementLadder = 0x6,
    eMovementPullVictimFromWindow = 0x7,
    eMovementFiberWireKill = 0x8,
    eMovementThrowBodyOverRail = 0x9,
    eMovementDumpBodyOverLedge = 0xA,
    eMovementDumpBody = 0xB,
    eMovementOperateCPDoor = 0xC,
    eMovementDisguiseSafeZone = 0xD,
    eMovementHideInCloset = 0xE,
    eMovementHumanShield = 0xF,
    eMovementCloseCombat = 0x10,
    eMovementDisableFuseBox = 0x11,
    eMovementContextAction = 0x12,
    eMovementInteractiveCutsequence = 0x13,
    eMovementVentilatorShaft = 0x14,
    eMovementPushVictimThroughWindowAndRail = 0x15,
    eMovementKickVictimOverLedge = 0x16,
    eMovementKeyCardReader = 0x17,
    eMovementDragBody = 0x18,
    eMovementTakeClothes = 0x19,
    eMovementCarryCivilian = 0x1A,
    eMovementToss = 0x1B,
    eMovementSurrender = 0x1C,
    eMovementUseHealthStation = 0x1D,
    eMovementPickupItem = 0x1E,
    eMovementLocomotion = 0x1F,
    eMovementLast = 0x20
};
