#pragma once

enum EBaseMovementType
{
	eMovementNone = -1,
	eMovementDead = 0,
	eMovementLedgeHang = 1,
	eMovementLedgeWalk = 2,
	eMovementClimbWindow = 3,
	eMovementShootingBallet = 4,
	eMovementCover = 5,
	eMovementLadder = 6,
	eMovementPullVictimFromWindow = 7,
	eMovementFiberWireKill = 8,
	eMovementThrowBodyOverRail = 9,
	eMovementDumpBodyOverLedge = 10,
	eMovementDumpBody = 11,
	eMovementOperateCPDoor = 12,
	eMovementDisguiseSafeZone = 13,
	eMovementHideInCloset = 14,
	eMovementHumanShield = 15,
	eMovementCloseCombat = 16,
	eMovementDisableFuseBox = 17,
	eMovementContextAction = 18,
	eMovementInteractiveCutsequence = 19,
	eMovementVentilatorShaft = 20,
	eMovementPushVictimThroughWindowAndRail = 21,
	eMovementKickVictimOverLedge = 22,
	eMovementKeyCardReader = 23,
	eMovementDragBody = 24,
	eMovementTakeClothes = 25,
	eMovementCarryCivilian = 26,
	eMovementToss = 27,
	eMovementSurrender = 28,
	eMovementUseHealthStation = 29,
	eMovementPickupItem = 30,
	eMovementLocomotion = 31,
	eMovementLast = 32
};
