#pragma once

enum EBCAnimSet : __int32
{
    BC_CONTAINER_STANDARD = 0x0,
    BC_CONTAINER_WOODCHIPPER = 0x1,
    BC_CAR_STANDARD_TRUNK = 0x2,
    BC_CONTAINER_CLOSET = 0x3,
    BC_CONTAINER_LAUNDRYCHUTE = 0x4
};
