#pragma once

enum ECCNodeType
{
	eCCNodeType_Counter = 0,
	eCCNodeType_ExecutePistol = 1,
	eCCNodeType_React = 2,
	eCCNodeType_SilentTakeDownEnd = 3,
	eCCNodeType_SilentKill = 4,
	eCCNodeType_SlitThroat1H = 5,
	eCCNodeType_Swing1H = 6,
	eCCNodeType_Bash1H = 7,
	eCCNodeType_Stab1H = 8,
	eCCNodeType_Syringe1H = 9,
	eCCNodeType_Strangle1H = 10,
	eCCNodeType_Smash1H = 11,
	eCCNodeType_Swing2H = 12,
	eCCNodeType_Stab2H = 13,
	eCCNodeType_Bash2H = 14,
	eCCNodeType_Strangle2H = 15,
	eCCNodeType_Axe = 16,
	eCCNodeType_AttackChain = 17,
	eCCNodeType_AttackChainCivilian = 18,
	eCCNodeType_AttackChainHeavy = 19,
	eCCNodeType_FailChain = 20,
	eCCNodeType_FinishChainHigh = 21,
	eCCNodeType_FinishChainLow = 22,
	eCCNodeType_FinishChainKill = 23,
	eCCNodeType_StairsChain = 24,
	eCCNodeType_CounterChain = 25,
	eCCNodeType_AttackIdle = 26,
	eCCNodeType_AttackPassify = 27,
	eCCNodeType_CoverLowOverTakeDown = 28,
	eCCNodeType_CoverLowThinOverTakeDown = 29,
	eCCNodeType_CoverLowThinOverFarTakeDown = 30,
	eCCNodeType_CoverLowCornerTakeDown = 31,
	eCCNodeType_CoverHighCornerTakeDown = 32,
	eCCNodeType_CoverChangeSideRight = 33,
	eCCNodeType_SilentTakeDown = 34,
	eCCNodeType_ChokeLoop = 35,
	eCCNodeType_ChokeKillSilent = 36,
	eCCNodeType_ChokeKillSnapNeck = 37,
	eCCNodeType_BossAttackChain = 38,
	eCCNodeType_BossAttackChainLoop = 39,
	eCCNodeType_BossAttackChainFinish = 40,
	eCCNodeType_BossCounterChain = 41,
	eCCNodeType_BossFailChain = 42,
	eCCNodeType_BossReact = 43,
	eCCNodeType_FailChainPush = 44,
	eCCNodeType_Count = 45
};
