#pragma once

enum ECompiledConditionType : __int32
{
    CT_IsCurrent = 0x0,
    CT_Current = 0x1,
    CT_IsExpired = 0x2,
    CT_MinExpired = 0x3,
    CT_MaxExpired = 0x4,
    CT_MinAge = 0x5,
    CT_MaxAge = 0x6,
    CT_IsSharedEventCurrent = 0x7,
    CT_SharedEventCurrent = 0x8,
    CT_MinSharedEventExpired = 0x9,
    CT_MinSharedEventAge = 0xA,
    CT_MaxSharedEventAge = 0xB,
    CT_IsNull = 0xC,
    CT_IsEqual = 0xD,
    CT_IsOfType = 0xE,
    CT_IsOfActorType = 0xF,
    CT_IsOfActorRank = 0x10,
    CT_HasGoal = 0x11,
    CT_HasTension = 0x12,
    CT_HasSameOutfit = 0x13,
    CT_MinDistance = 0x14,
    CT_MaxDistance = 0x15,
    CT_MinActualDistance = 0x16,
    CT_MaxActualDistance = 0x17,
    CT_ActualInsideSlice = 0x18,
    CT_InSituation = 0x19,
    CT_SituationTarget = 0x1A,
    CT_SituationFromActors = 0x1B,
    CT_SituationFromTarget = 0x1C,
    CT_MaxSituationAge = 0x1D,
    CT_MinSituationAge = 0x1E,
    CT_InPhase = 0x1F,
    CT_MinPhaseAge = 0x20,
    CT_MaxPhaseAge = 0x21,
    CT_IsOrderInvalid = 0x22,
    CT_Breakpoint = 0x23,
    CT_Cooldown = 0x24,
    CT_Trigger = 0x25
};
