#pragma once

enum ECommand : __int32
{
    COMMAND_START = 0x0,
    COMMAND_ENABLE_PREVIEW = 0x1,
    COMMAND_STOP = 0x2,
    COMMAND_DISABLE_PREVIEW = 0x3,
    COMMAND_ABORT = 0x4,
    COMMAND_PAUSE = 0x5,
    COMMAND_UNPAUSE = 0x6,
    COMMAND_SETTIME = 0x7,
    COMMAND_GAME_PAUSE = 0x8,
    COMMAND_GAME_UNPAUSE = 0x9,
    COMMAND_PREVIEW_PAUSE = 0xA,
    COMMAND_PREVIEW_STOP = 0xB,
    COMMAND_PREVIEW_PLAY = 0xC,
    COMMAND_PREVIEW_LOOPED = 0xD,
};
