#pragma once

enum ECompiledConditionType
{
	CT_IsCurrent = 0,
	CT_Current = 1,
	CT_IsExpired = 2,
	CT_MinExpired = 3,
	CT_MaxExpired = 4,
	CT_MinAge = 5,
	CT_MaxAge = 6,
	CT_IsSharedEventCurrent = 7,
	CT_SharedEventCurrent = 8,
	CT_MinSharedEventExpired = 9,
	CT_MinSharedEventAge = 10,
	CT_MaxSharedEventAge = 11,
	CT_IsNull = 12,
	CT_IsEqual = 13,
	CT_IsOfType = 14,
	CT_IsOfActorType = 15,
	CT_IsOfActorRank = 16,
	CT_HasGoal = 17,
	CT_HasTension = 18,
	CT_HasSameOutfit = 19,
	CT_MinDistance = 20,
	CT_MaxDistance = 21,
	CT_MinActualDistance = 22,
	CT_MaxActualDistance = 23,
	CT_ActualInsideSlice = 24,
	CT_InSituation = 25,
	CT_SituationTarget = 26,
	CT_SituationFromActors = 27,
	CT_SituationFromTarget = 28,
	CT_MaxSituationAge = 29,
	CT_MinSituationAge = 30,
	CT_InPhase = 31,
	CT_MinPhaseAge = 32,
	CT_MaxPhaseAge = 33,
	CT_IsOrderInvalid = 34,
	CT_Breakpoint = 35,
	CT_Cooldown = 36,
	CT_Trigger = 37
};
