#pragma once

enum EControllerButton
{
	BUTTON_NONE = 0,
	BUTTON_CROSS = 1,
	BUTTON_TRIANGLE = 2,
	BUTTON_SQUARE = 3,
	BUTTON_CIRCLE = 4,
	BUTTON_UP = 5,
	BUTTON_RIGHT = 6,
	BUTTON_DOWN = 7,
	BUTTON_LEFT = 8,
	BUTTON_R1 = 9,
	BUTTON_R2 = 10,
	BUTTON_R3 = 11,
	BUTTON_R_STICK = 12,
	BUTTON_L1 = 13,
	BUTTON_L2 = 14,
	BUTTON_L3 = 15,
	BUTTON_L_STICK = 16,
	BUTTON_START = 17,
	BUTTON_SELECT = 18,
	BUTTON_UP_DOWN = 19,
	BUTTON_LEFT_RIGHT = 20,
	BUTTON_LEFT_RIGHT_UP_DOWN = 21,
	BUTTON_L1_R1 = 22,
	BUTTON_L2_R2 = 23,
	BUTTON_KEYBOARD = 24,
	BUTTON_ESCAPE = 25
};
