#pragma once

enum EConstraintType : __int32
{
    ECONSTRAINTTYPE_UNKNOWN = 0x0,
    ECONSTRAINTTYPE_BALL_AND_SOCKET = 0x1,
    ECONSTRAINTTYPE_HINGE = 0x2,
    ECONSTRAINTTYPE_FIXED = 0x3,
    ECONSTRAINTTYPE_DISTANCE = 0x4,
    ECONSTRAINTTYPE_D6 = 0x5
};
