#pragma once

enum EConstraintType
{
	ECONSTRAINTTYPE_UNKNOWN = 0,
	ECONSTRAINTTYPE_BALL_AND_SOCKET = 1,
	ECONSTRAINTTYPE_HINGE = 2,
	ECONSTRAINTTYPE_FIXED = 3,
	ECONSTRAINTTYPE_DISTANCE = 4,
	ECONSTRAINTTYPE_D6 = 5
};
