#pragma once

enum EControllerDirtyFlags : __int32
{
    EMITTER_CONST_SIZE_DIRTY = 0x1,
    MODIFIER_CONST_SIZE_DIRTY = 0x2,
    PROPERTIES_DIRTY = 0x4,
    NUM_DEAD_NEEDED_DIRTY = 0x8,
    MODIFIERS_DIRTY = 0x10,
    EMITTERS_DIRTY = 0x20,
    JUST_DIRTY = 0x40,
    EMITTER_SHADER_MASK_DIRTY = 0x80,
    MODIFIER_SHADER_MASK_DIRTY = 0x100,
    ALL_DIRTY = 0x1FF
};
