#pragma once

enum EControllerDirtyFlagShifts : __int32
{
    EMITTER_CONST_SIZE_DIRTY_SHIFT = 0x0,
    MODIFIER_CONST_SIZE_DIRTY_SHIFT = 0x1,
    PROPERTIES_DIRTY_SHIFT = 0x2,
    NUM_DEAD_NEEDED_DIRTY_SHIFT = 0x3,
    MODIFIERS_DIRTY_SHIFT = 0x4,
    EMITTERS_DIRTY_SHIFT = 0x5,
    JUST_DIRTY_SHIFT = 0x6,
    EMITTER_SHADER_MASK_DIRTY_SHIFT = 0x7,
    MODIFIER_SHADER_MASK_DIRTY_SHIFT = 0x8
};
