#pragma once

enum EControllerButton : __int32
{
    BUTTON_NONE = 0x0,
    BUTTON_CROSS = 0x1,
    BUTTON_TRIANGLE = 0x2,
    BUTTON_SQUARE = 0x3,
    BUTTON_CIRCLE = 0x4,
    BUTTON_UP = 0x5,
    BUTTON_RIGHT = 0x6,
    BUTTON_DOWN = 0x7,
    BUTTON_LEFT = 0x8,
    BUTTON_R1 = 0x9,
    BUTTON_R2 = 0xA,
    BUTTON_R3 = 0xB,
    BUTTON_R_STICK = 0xC,
    BUTTON_L1 = 0xD,
    BUTTON_L2 = 0xE,
    BUTTON_L3 = 0xF,
    BUTTON_L_STICK = 0x10,
    BUTTON_START = 0x11,
    BUTTON_SELECT = 0x12,
    BUTTON_UP_DOWN = 0x13,
    BUTTON_LEFT_RIGHT = 0x14,
    BUTTON_LEFT_RIGHT_UP_DOWN = 0x15,
    BUTTON_L1_R1 = 0x16,
    BUTTON_L2_R2 = 0x17,
    BUTTON_KEYBOARD = 0x18,
    BUTTON_ESCAPE = 0x19
};
