#pragma once

enum EDefaultCollidableLayer
{
	DCL_STATIC = 0,
	DCL_KINEMATIC = 1,
	DCL_KINEMATIC_TRANSPARENT = 2,
	DCL_DYNAMIC = 3,
	DCL_DYNAMIC_TRANSPARENT = 4,
	DCL_AUXILIARY = 5,
	DCL_UNUSED_LAST = 6
};
