#pragma once

enum EGameEventArgType
{
	GE_ARGS_KILL = 0,
	GE_ARGS_PRIORITYKILL = 1,
	GE_ARGS_SITUATION = 2,
	GE_ARGS_INVENTORY = 3,
	GE_ARGS_SHOOTINGBALLET = 4,
	GE_ARGS_EXPLODINGPROP = 5,
	GE_ARGS_EVENT = 6,
	GE_ARGS_CHECKPOINTEVENT = 7,
	GE_ARGS_COUNT = 8
};
