#pragma once

enum EHitmanGState
{
	eHGS_Reserved_QueryALL = 0,
	eHGS_Reserved_QueryAny = 1,
	eHGS_InstinctModeActive = 2,
	eHGS_BlendInCanStart = 3,
	eHGS_BlendInActive = 4,
	eHGS_IsHardToSee = 5,
	eHGS_Sneaking = 6,
	eHGS_InCloseCombat = 7,
	eHGS_ItemHandlingActive = 8,
	eHGS_CamSwitched = 9,
	eHGS_SniperMode = 10,
	eHGS_OTSMode = 11,
	eHGS_DualWielding = 12,
	eHGS_ActivatingAltFire = 13,
	eHGS_FiredLastFrFocusBurnRate = 14,
	eHGS_FiredLastFrFocusGainValue = 15,
	eHGS_BurningFocus = 16,
	eHGS_InsideCloset = 17,
	eHGS_HoldsUtility = 18,
	eHGS_MvAgility = 19,
	eHGS_MvCover = 20,
	eHGS_MvDragging = 21,
	eHGS_MvHumanShield = 22,
	eHGS_MvCarryCivilian = 23,
	eHGS_MvVentilatorShaft = 24,
	eHGS_MvLedgeWalk = 25,
	eHGS_MvLedgeHang = 26,
	eHGS_MvLocomotion = 27,
	eHGS_MvShootingBallet = 28,
	eHGS_MvCloseCombat = 29,
	eHGS_MvSurrendering = 30,
	eHGS_NUM = 31
};
