#pragma once

enum EHMAttentionType
{
	eHMA_UNKNOWN = 0,
	eHMA_TRESSPASSING = 1,
	eHMA_ILLEGALACTION = 2,
	eHMA_FORCEDILLEGAL = 3,
	eHMA_COMBAT = 4,
	eHMA_HUNTING = 5,
	eHMA_DISGUISE = 6,
	eHMA_DEADBODY = 7,
	eHMA_FORCEDFULL = 8,
	eHMA_MAX = 9
};
