#pragma once

enum ENetworkControlParam : __int32
{
    eNetworkControlParam_StandWalkSelect = 0x0,
    eNetworkControlParam_WalkRunSelect = 0x1,
    eNetworkControlParam_TurnSelect = 0x2,
    eNetworkControlParam_LeftRightSelect = 0x3,
    eNetworkControlParam_StopMatchEventsSelect = 0x4,
    eNetworkControlParam_TranslationSelect = 0x5,
    eNetworkControlParam_DestinationEventSelect = 0x6,
    eNetworkControlParam_SmallStepBlend = 0x7,
    eNetworkControlParam_WalkRunBlend = 0x8,
    eNetworkControlParam_MoveFastBlend = 0x9,
    eNetworkControlParam_SneakBlend = 0xA,
    eNetworkControlParam_MoveTrajectoryScale = 0xB,
    eNetworkControlParam_StandTurnLeftRight = 0xC,
    eNetworkControlParam_StandTurnFraction = 0xD,
    eNetworkControlParam_StandTurn = 0xE,
    eNetworkControlParam_StandTurnAngle = 0xF,
    eNetworkControlParam_Bank = 0x10,
    eNetworkControlParam_HeadDirection = 0x11,
    eNetworkControlParam_TorsoDirection = 0x12,
    eNetworkControlParam_HipsDirection = 0x13,
    eNetworkControlParam_MoveTurnAngle = 0x14,
    eNetworkControlParam_SneakTranslation = 0x15,
    eNetworkControlParam_FootStepTriggered = 0x16,
    eNetworkControlParam_StrafeTrajectory = 0x17,
    eNetworkControlParam_StrafeForwardSelect = 0x18,
    eNetworkControlParam_StrafeBackwardSelect = 0x19,
    eNetworkControlParam_StrafeSpeed = 0x1A,
    eNetworkControlParam_AssaultRifle = 0x1B,
    eNetworkControlParam_SingleWeapon = 0x1C,
    eNetworkControlParam_CarryFireArm = 0x1D,
    eNetworkControlParam_IdleAnimIndex = 0x1E,
    eNetworkControlParam_Random = 0x1F,
    eNetworkControlParam_Count = 0x20
};
