#pragma once

enum ESaveLoadSlotStatus
{
	eSAVELOADSLOTSTATUS_OK = 0,
	eSAVELOADSLOTSTATUS_PROCESSING = 1,
	eSAVELOADSLOTSTATUS_MISSING = 2,
	eSAVELOADSLOTSTATUS_ERROR_NODISKSPACE = 3,
	eSAVELOADSLOTSTATUS_ERROR_DEVICEREMOVED = 4,
	eSAVELOADSLOTSTATUS_ERROR_CORRUPT = 5,
	eSAVELOADSLOTSTATUS_ERROR_SAVING = 6,
	eSAVELOADSLOTSTATUS_ERROR_FATAL = 7
};
