#pragma once

enum ESaveLoadSlotStatus : __int32
{
    eSAVELOADSLOTSTATUS_OK = 0x0,
    eSAVELOADSLOTSTATUS_PROCESSING = 0x1,
    eSAVELOADSLOTSTATUS_MISSING = 0x2,
    eSAVELOADSLOTSTATUS_ERROR_NODISKSPACE = 0x3,
    eSAVELOADSLOTSTATUS_ERROR_DEVICEREMOVED = 0x4,
    eSAVELOADSLOTSTATUS_ERROR_CORRUPT = 0x5,
    eSAVELOADSLOTSTATUS_ERROR_SAVING = 0x6,
    eSAVELOADSLOTSTATUS_ERROR_FATAL = 0x7
};
