#pragma once

enum ESingletonIconType : __int32
{
    SINGLETON_ICON_TYPE_NONE = 0x0,
    SINGLETON_ICON_TYPE_CHALLENGE = 0x1,
    SINGLETON_ICON_TYPE_OBJECTIVE = 0x2,
    SINGLETON_ICON_TYPE_CHECKPOINT = 0x3,
    SINGLETON_ICON_TYPE_LEVEL = 0x4,
    SINGLETON_ICON_TYPE_RATING = 0x5,
    SINGLETON_ICON_TYPE_TECHNIQUE = 0x6,
    SINGLETON_ICON_TYPE_DISGUISE = 0x7,
    SINGLETON_ICON_TYPE_WEAPON = 0x8,
    SINGLETON_ICON_TYPE_PROP = 0x9
};
