#pragma once

enum ESingletonIconType
{
	SINGLETON_ICON_TYPE_NONE = 0,
	SINGLETON_ICON_TYPE_CHALLENGE = 1,
	SINGLETON_ICON_TYPE_OBJECTIVE = 2,
	SINGLETON_ICON_TYPE_CHECKPOINT = 3,
	SINGLETON_ICON_TYPE_LEVEL = 4,
	SINGLETON_ICON_TYPE_RATING = 5,
	SINGLETON_ICON_TYPE_TECHNIQUE = 6,
	SINGLETON_ICON_TYPE_DISGUISE = 7,
	SINGLETON_ICON_TYPE_WEAPON = 8,
	SINGLETON_ICON_TYPE_PROP = 9
};
