#pragma once

enum ESustainPointState
{
	SUSTAIN_POINT_MANUAL = 0,
	SUSTAIN_POINT_READYTOSTART = 1,
	SUSTAIN_POINT_BEFORE = 2,
	SUSTAIN_POINT_AT = 3,
	SUSTAIN_POINT_AFTER = 4,
	SUSTAIN_POINT_ENDREACHED = 5
};
