#pragma once

enum EThrowType : __int32
{
    eThrowTypeStandNormal = 0x0,
    eThrowTypeStandNormal90Right = 0x1,
    eThrowTypeCrouchNormal = 0x2,
    eThrowTypeCrouchNormal90Right = 0x3,
    eThrowTypeCoverNormalHighLeft = 0x4,
    eThrowTypeCoverNormalHighRight = 0x5,
    eThrowTypeCoverNormalLowLeft = 0x6,
    eThrowTypeCoverNormalLowRight = 0x7,
    eThrowTypeCoverNormalHighLeft180 = 0x8,
    eThrowTypeCoverNormalHighRight180 = 0x9,
    eThrowTypeCoverNormalLowLeft180 = 0xA,
    eThrowTypeCoverNormalLowRight180 = 0xB,
    eThrowTypeStandDeadly135Left = 0xC,
    eThrowTypeStandDeadly = 0xD,
    eThrowTypeStandDeadly135Right = 0xE,
    eThrowTypeCrouchDeadly135Left = 0xF,
    eThrowTypeCrouchDeadly = 0x10,
    eThrowTypeCrouchDeadly135Right = 0x11,
    eThrowTypeStandDeadlyHeavy135Left = 0x12,
    eThrowTypeStandDeadlyHeavy = 0x13,
    eThrowTypeStandDeadlyHeavy135Right = 0x14,
    eThrowTypeCrouchDeadlyHeavy135Left = 0x15,
    eThrowTypeCrouchDeadlyHeavy = 0x16,
    eThrowTypeCrouchDeadlyHeavy135Right = 0x17,
    eThrowTypeCoverDeadlyHighLeft = 0x18,
    eThrowTypeCoverDeadlyHighRight = 0x19,
    eThrowTypeCoverDeadlyLowLeft = 0x1A,
    eThrowTypeCoverDeadlyLowRight = 0x1B,
    eThrowTypeCoverDeadlyHeavyHighLeft = 0x1C,
    eThrowTypeCoverDeadlyHighLeft180 = 0x1D,
    eThrowTypeCoverDeadlyHeavyHighRight = 0x1E,
    eThrowTypeCoverDeadlyHighRight180 = 0x1F,
    eThrowTypeCoverDeadlyHeavyLowLeft = 0x20,
    eThrowTypeCoverDeadlyLowLeft180 = 0x21,
    eThrowTypeCoverDeadlyHeavyLowRight = 0x22,
    eThrowTypeCoverDeadlyLowRight180 = 0x23,
    eThrowTypeCoverDeadlyHeavyHighRight180 = 0x24,
    eThrowTypeCoverDeadlyHeavyHighLeft180 = 0x25,
    eThrowTypeCoverDeadlyHeavyLowRight180 = 0x26,
    eThrowTypeCoverDeadlyHeavyLowLeft180 = 0x27,
    eThrowTypeLast = 0x28
};
