#pragma once

struct InputControlNamesp
{
    enum eHM5InputAction : __int32
    {
        eIAButtonFaceDown_Downedge = 0x0,
        eIAButtonFaceDown_FastTap = 0x1,
        eIAButtonFaceDown_HldDwnOnce = 0x2,
        eIAButtonFaceDown_Hold = 0x3,
        eIAButtonFaceDown_HoldDown = 0x4,
        eIAButtonFaceLeft_Downedge = 0x5,
        eIAButtonFaceLeft_HldDwnOnce = 0x6,
        eIAButtonFaceLeft_Hold = 0x7,
        eIAButtonFaceLeft_FastTap = 0x8,
        eIAButtonFaceLeft_Tap = 0x9,
        eIAButtonFaceRight_Downedge = 0xA,
        eIAButtonFaceRight_HldDwnOnce = 0xB,
        eIAButtonFaceRight_Hold = 0xC,
        eIAButtonFaceRight_FastTap = 0xD,
        eIAButtonFaceRight_Tap = 0xE,
        eIAButtonFaceUp_Downedge = 0xF,
        eIAButtonFaceUp_FastTap = 0x10,
        eIAButtonFaceUp_HldDwnOnce = 0x11,
        eIAButtonFaceUp_Hold = 0x12,
        eIABumperLeft_FastTap = 0x13,
        eIABumperLeft_Hold = 0x14,
        eIABumperRight_FastTap = 0x15,
        eIABumperRight_Hold = 0x16,
        eIADpadUp_Downedge = 0x17,
        eIADpadDown_Downedge = 0x18,
        eIADpadDown_FastTap = 0x19,
        eIADpadDown_HldDwnOnce = 0x1A,
        eIADpadLeft_Downedge = 0x1B,
        eIADpadRight_Downedge = 0x1C,
        eIAThumbRight_Downedge = 0x1D,
        eIAThumbLeft_Hold = 0x1E,
        eIAThumbLeft_DownEdge = 0x1F,
        eIATriggerLeft_FastTap = 0x20,
        eIATriggerLeft_Hold = 0x21,
        eIATriggerRight_FastTap = 0x22,
        eIATriggerRight_Hold = 0x23,
        eIAGenericStart_Hold = 0x24,
        eIAKBMMoveUp = 0x25,
        eIAKBMMoveDown = 0x26,
        eIAKBMMoveLeft = 0x27,
        eIAKBMMoveRight = 0x28,
        eIAKBMUse = 0x29,
        eIAKBMUseHold = 0x2A,
        eIAKBMHumanShield = 0x2B,
        eIAKBMHumanShieldHold = 0x2C,
        eIAKBMPickup = 0x2D,
        eIAKBMCover = 0x2E,
        eIAKBMDragBody = 0x2F,
        eIAKBMMelee = 0x30,
        eIAKBMTakeDisguise = 0x31,
        eIAKBMRun = 0x32,
        eIAKBMAim = 0x33,
        eIAKBMShoot = 0x34,
        eIAKBMReload = 0x35,
        eIAKBMInstinct = 0x36,
        eIAKBMCamSwitch = 0x37,
        eIAKBMSneak = 0x38,
        eIAKBMHolster = 0x39,
        eIAKBMFireMode = 0x3A,
        eIAKBMNotebook = 0x3B,
        eIAKBMPause = 0x3C,
        eIAKBMWeapon1 = 0x3D,
        eIAKBMWeapon2 = 0x3E,
        eIAKBMWeapon3 = 0x3F,
        eIAKBMWeapon4 = 0x40,
        eIAKBMWeapon5 = 0x41,
        eIAKBMWeapon6 = 0x42,
        eIAKBMWeapon7 = 0x43,
        eIAKBMNextWeapon = 0x44,
        eIAKBMPreviousWeapon = 0x45,
        eIAKBMPrecisionAim = 0x46,
        eIAKBMZoomIn = 0x47,
        eIAKBMZoomOut = 0x48,
        eIAKBMDropItem = 0x49,
        eIAKBMMarkTarget = 0x4A,
        eIAKBMShowWeaponSelector = 0x4B,
        eIAKBMSwitchCover = 0x4C,
        eIAKBMOkay = 0x4D,
        eIAKBMCancel = 0x4E,
        eIATriggerLeft_Analog = 0x4F,
        eIATriggerRight_Analog = 0x50,
        eIAStickLeftHorizontal_Analog = 0x51,
        eIAStickLeftVertical_Analog = 0x52,
        eIAStickRightHorizontal_Analog = 0x53,
        eIAStickRightVertical_Analog = 0x54,
        eIAStickLeftHorizontal_Raw = 0x55,
        eIAStickLeftVertical_Raw = 0x56,
        eIAStickRightHorizontal_Raw = 0x57,
        eIAStickRightVertical_Raw = 0x58,
        eIABumperLeft_Analog = 0x59,
        eIABumperRight_Analog = 0x5A,
        eIAKBMMoveHorizontal = 0x5B,
        eIAKBMMoveVertical = 0x5C,
        eIAKBMLookHorizontal = 0x5D,
        eIAKBMLookVertical = 0x5E,
        eIActionsNUM = 0x5F
    };

    enum eHM5InputActionID : __int32
    {
        eIDButtonFaceDown = 0x0,
        eIDButtonFaceLeft = 0x1,
        eIDButtonFaceRight = 0x2,
        eIDButtonFaceUp = 0x3,
        eIDBumperLeft = 0x4,
        eIDBumperRight = 0x5,
        eIDDpadDown = 0x6,
        eIDDpadLeft = 0x7,
        eIDDpadRight = 0x8,
        eIDDpadUp = 0x9,
        eIDThumbLeft = 0xA,
        eIDThumbRight = 0xB,
        eIDButtonStart = 0xC,
        eIDButtonSelect = 0xD,
        eIDTriggerLeft = 0xE,
        eIDTriggerRight = 0xF,
        eIDStickLeftHorizontal = 0x10,
        eIDStickLeftVertical = 0x11,
        eIDStickRightHorizontal = 0x12,
        eIDStickRightVertical = 0x13,
        eIDKeyboard = 0x14,
        eID_INVALID = 0x15
    };

    enum eHM5InputActionType : __int32
    {
        eTypeGet = 0x0,
        eTypeHold = 0x1,
        eTypeRepeat = 0x2,
        eTypeTap = 0x3,
        eTypeRelease = 0x4,
        eTypeDownedge = 0x5,
        eTypeFastTap = 0x6,
        eTypeHoldDown = 0x7,
        eTypeFireOnceHoldDown = 0x8,
        eTypeClickHold = 0x9,
        eTypePress = 0xA,
        eTypeANALOG = 0xB,
        eTypeANALOGRAW = 0xC,
        eTypeRELATIVE = 0xD,
        eTYPE_INVALID = 0xE
    };
};