#pragma once

namespace InputControlNamesp
{
	enum eHM5InputAction
	{
		eIAButtonFaceDown_Downedge = 0,
		eIAButtonFaceDown_FastTap = 1,
		eIAButtonFaceDown_HldDwnOnce = 2,
		eIAButtonFaceDown_Hold = 3,
		eIAButtonFaceDown_HoldDown = 4,
		eIAButtonFaceLeft_Downedge = 5,
		eIAButtonFaceLeft_HldDwnOnce = 6,
		eIAButtonFaceLeft_Hold = 7,
		eIAButtonFaceLeft_FastTap = 8,
		eIAButtonFaceLeft_Tap = 9,
		eIAButtonFaceRight_Downedge = 10,
		eIAButtonFaceRight_HldDwnOnce = 11,
		eIAButtonFaceRight_Hold = 12,
		eIAButtonFaceRight_FastTap = 13,
		eIAButtonFaceRight_Tap = 14,
		eIAButtonFaceUp_Downedge = 15,
		eIAButtonFaceUp_FastTap = 16,
		eIAButtonFaceUp_HldDwnOnce = 17,
		eIAButtonFaceUp_Hold = 18,
		eIABumperLeft_FastTap = 19,
		eIABumperLeft_Hold = 20,
		eIABumperRight_FastTap = 21,
		eIABumperRight_Hold = 22,
		eIADpadUp_Downedge = 23,
		eIADpadDown_Downedge = 24,
		eIADpadDown_FastTap = 25,
		eIADpadDown_HldDwnOnce = 26,
		eIADpadLeft_Downedge = 27,
		eIADpadRight_Downedge = 28,
		eIAThumbRight_Downedge = 29,
		eIAThumbLeft_Hold = 30,
		eIAThumbLeft_DownEdge = 31,
		eIATriggerLeft_FastTap = 32,
		eIATriggerLeft_Hold = 33,
		eIATriggerRight_FastTap = 34,
		eIATriggerRight_Hold = 35,
		eIAGenericStart_Hold = 36,
		eIAKBMMoveUp = 37,
		eIAKBMMoveDown = 38,
		eIAKBMMoveLeft = 39,
		eIAKBMMoveRight = 40,
		eIAKBMUse = 41,
		eIAKBMUseHold = 42,
		eIAKBMHumanShield = 43,
		eIAKBMHumanShieldHold = 44,
		eIAKBMPickup = 45,
		eIAKBMCover = 46,
		eIAKBMDragBody = 47,
		eIAKBMMelee = 48,
		eIAKBMTakeDisguise = 49,
		eIAKBMRun = 50,
		eIAKBMAim = 51,
		eIAKBMShoot = 52,
		eIAKBMReload = 53,
		eIAKBMInstinct = 54,
		eIAKBMCamSwitch = 55,
		eIAKBMSneak = 56,
		eIAKBMHolster = 57,
		eIAKBMFireMode = 58,
		eIAKBMNotebook = 59,
		eIAKBMPause = 60,
		eIAKBMWeapon1 = 61,
		eIAKBMWeapon2 = 62,
		eIAKBMWeapon3 = 63,
		eIAKBMWeapon4 = 64,
		eIAKBMWeapon5 = 65,
		eIAKBMWeapon6 = 66,
		eIAKBMWeapon7 = 67,
		eIAKBMNextWeapon = 68,
		eIAKBMPreviousWeapon = 69,
		eIAKBMPrecisionAim = 70,
		eIAKBMZoomIn = 71,
		eIAKBMZoomOut = 72,
		eIAKBMDropItem = 73,
		eIAKBMMarkTarget = 74,
		eIAKBMShowWeaponSelector = 75,
		eIAKBMSwitchCover = 76,
		eIAKBMOkay = 77,
		eIAKBMCancel = 78,
		eIATriggerLeft_Analog = 79,
		eIATriggerRight_Analog = 80,
		eIAStickLeftHorizontal_Analog = 81,
		eIAStickLeftVertical_Analog = 82,
		eIAStickRightHorizontal_Analog = 83,
		eIAStickRightVertical_Analog = 84,
		eIAStickLeftHorizontal_Raw = 85,
		eIAStickLeftVertical_Raw = 86,
		eIAStickRightHorizontal_Raw = 87,
		eIAStickRightVertical_Raw = 88,
		eIABumperLeft_Analog = 89,
		eIABumperRight_Analog = 90,
		eIAKBMMoveHorizontal = 91,
		eIAKBMMoveVertical = 92,
		eIAKBMLookHorizontal = 93,
		eIAKBMLookVertical = 94,
		eIActionsNUM = 95
	};

	enum eHM5InputActionID
	{
		eIDButtonFaceDown = 0,
		eIDButtonFaceLeft = 1,
		eIDButtonFaceRight = 2,
		eIDButtonFaceUp = 3,
		eIDBumperLeft = 4,
		eIDBumperRight = 5,
		eIDDpadDown = 6,
		eIDDpadLeft = 7,
		eIDDpadRight = 8,
		eIDDpadUp = 9,
		eIDThumbLeft = 10,
		eIDThumbRight = 11,
		eIDButtonStart = 12,
		eIDButtonSelect = 13,
		eIDTriggerLeft = 14,
		eIDTriggerRight = 15,
		eIDStickLeftHorizontal = 16,
		eIDStickLeftVertical = 17,
		eIDStickRightHorizontal = 18,
		eIDStickRightVertical = 19,
		eIDKeyboard = 20,
		eID_INVALID = 21
	};

	enum eHM5InputActionType
	{
		eTypeGet = 0,
		eTypeHold = 1,
		eTypeRepeat = 2,
		eTypeTap = 3,
		eTypeRelease = 4,
		eTypeDownedge = 5,
		eTypeFastTap = 6,
		eTypeHoldDown = 7,
		eTypeFireOnceHoldDown = 8,
		eTypeClickHold = 9,
		eTypePress = 10,
		eTypeANALOG = 11,
		eTypeANALOGRAW = 12,
		eTypeRELATIVE = 13,
		eTYPE_INVALID = 14
	};
};