#pragma once

enum StateType : __int32
{
    State_None = 0x0,
    State_RenderConfig = 0x1,
    State_RenderStats = 0x2,
    State_Translator = 0x3,
    State_Log = 0x4,
    State_ImageLoader = 0x5,
    State_ActionControl = 0x6,
    State_UserEventHandler = 0x7,
    State_FSCommandHandler = 0x8,
    State_ExternalInterface = 0x9,
    State_FileOpener = 0xA,
    State_URLBuilder = 0xB,
    State_ImageCreator = 0xC,
    State_ParseControl = 0xD,
    State_ProgressHandler = 0xE,
    State_ImportVisitor = 0xF,
    State_MeshCacheManager = 0x10,
    State_FontPackParams = 0x11,
    State_FontCacheManager = 0x12,
    State_FontLib = 0x13,
    State_FontProvider = 0x14,
    State_FontMap = 0x15,
    State_GradientParams = 0x16,
    State_TaskManager = 0x17,
    State_TextClipboard = 0x18,
    State_TextKeyMap = 0x19,
    State_PreprocessParams = 0x1A,
    State_IMEManager = 0x1B,
    State_XMLSupport = 0x1C,
    State_JpegSupport = 0x1D,
    State_ZlibSupport = 0x1E,
    State_FontCompactorParams = 0x1F,
    State_ImagePackerParams = 0x20,
    State_PNGSupport = 0x21,
    State_Audio = 0x22,
    State_Video = 0x23,
    State_TestStream = 0x24,
    State_SharedObject = 0x25,
    State_LocSupport = 0x26
};
