#pragma once

enum EEntityTypeMapFlags
{
	ENTITYTYPE_PROPERTY_MAP = 1,
	ENTITYTYPE_INTERFACE_MAP = 2,
	ENTITYTYPE_EXPENT_MAP = 4,
	ENTITYTYPE_SUBSET_MAP = 8,
	ENTITYTYPE_INPUTPIN_MAP = 16,
	ENTITYTYPE_OUTPUTPIN_MAP = 32,
	ENTITYTYPE_OWNED_BY_ENTITY = 64
};
