#pragma once

enum EResourceStatus : __int32
{
    RESOURCE_STATUS_UNKNOWN = 0x0,
    RESOURCE_STATUS_LOADING = 0x1,
    RESOURCE_STATUS_INSTALLING = 0x2,
    RESOURCE_STATUS_FAILED = 0x3,
    RESOURCE_STATUS_VALID = 0x4,
    RESOURCE_STATUS_HEADER_LOADED = 0x5
};
