#pragma once

enum EWeaponUpgradeIcon
{
	WEAPON_UPGRADE_ICON_NONE = 0,
	WEAPON_UPGRADE_ICON_SILENCER = 1,
	WEAPON_UPGRADE_ICON_RED_DOT_SIGHT = 2,
	WEAPON_UPGRADE_ICON_AMMUNITION = 3,
	WEAPON_UPGRADE_ICON_MAGAZINE = 4,
	WEAPON_UPGRADE_ICON_EXTCLIP = 5,
	WEAPON_UPGRADE_ICON_SHELLS = 6,
	WEAPON_UPGRADE_ICON_SLIDE = 7,
	WEAPON_UPGRADE_ICON_BOLT = 8,
	WEAPON_UPGRADE_ICON_BARREL = 9,
	WEAPON_UPGRADE_ICON_HAMMER = 10,
	WEAPON_UPGRADE_ICON_CHUTE = 11,
	WEAPON_UPGRADE_ICON_DUALWIELD = 12,
	WEAPON_UPGRADE_ICON_MAGNUM = 13,
	WEAPON_UPGRADE_ICON_STOCK = 14
};
