#pragma once

enum EWeaponUpgradeIcon : __int32
{
    WEAPON_UPGRADE_ICON_NONE = 0x0,
    WEAPON_UPGRADE_ICON_SILENCER = 0x1,
    WEAPON_UPGRADE_ICON_RED_DOT_SIGHT = 0x2,
    WEAPON_UPGRADE_ICON_AMMUNITION = 0x3,
    WEAPON_UPGRADE_ICON_MAGAZINE = 0x4,
    WEAPON_UPGRADE_ICON_EXTCLIP = 0x5,
    WEAPON_UPGRADE_ICON_SHELLS = 0x6,
    WEAPON_UPGRADE_ICON_SLIDE = 0x7,
    WEAPON_UPGRADE_ICON_BOLT = 0x8,
    WEAPON_UPGRADE_ICON_BARREL = 0x9,
    WEAPON_UPGRADE_ICON_HAMMER = 0xA,
    WEAPON_UPGRADE_ICON_CHUTE = 0xB,
    WEAPON_UPGRADE_ICON_DUALWIELD = 0xC,
    WEAPON_UPGRADE_ICON_MAGNUM = 0xD,
    WEAPON_UPGRADE_ICON_STOCK = 0xE
};
