#pragma once

enum EGSKillSituation
{
	GSKILLSITUATION_UNKNOWN = 0,
	GSKILLSITUATION_CLOSECOMBAT = 1,
	GSKILLSITUATION_SILENT = 2,
	GSKILLSITUATION_ENVIRONMENT = 3,
	GSKILLSITUATION_ACTION = 4,
	GSKILLSITUATION_SHOOTINGBALLET = 5,
	GSKILLSITUATION_DEADLYTHROW = 6,
	GSKILLSITUATION_PULLTHROUGHWINDOW = 7,
	GSKILLSITUATION_PUSHOVERRAILING = 8,
	GSKILLSITUATION_PACIFY = 9,
	GSKILLSITUATION_FIBERWIRE = 10,
	GSKILLSITUATION_COUNT = 11
};
