#pragma once

enum ECameraState
{
	eCamSneakStand = 0,
	eCamSneakWalk = 1,
	eCamSneakRoadyRun = 2,
	eCamNormalStand = 3,
	eCamNormalWalk = 4,
	eCamNormalRun = 5,
	eCamLocomotion = 6,
	eCamCrowdStand = 7,
	eCamCrowdWalk = 8,
	eCamCrowdRun = 9,
	eCamCrowdSneakStand = 10,
	eCamCrowdSneakWalk = 11,
	eCamCrowdSneakRoadyRun = 12,
	eCamCrowdLocomotion = 13,
	eCamDead = 14,
	eCamLadder = 15,
	eCamDrag = 16,
	eCamHumanShield = 17,
	eCamSBTag = 18,
	eCamSBTagOTS = 19,
	eCamCloseCombat = 20,
	eCamFiberWire = 21,
	eCamWindowPull = 22,
	eCamRailPush = 23,
	eCamLedgeKick = 24,
	eCamLedgePull = 25,
	eCamLedgeHang = 26,
	eCamLedgeWalk = 27,
	eCamLedgeWalkOTS = 28,
	eCamCoverLow = 29,
	eCamCoverMedium = 30,
	eCamCoverHigh = 31,
	eCamCoverLowOTS = 32,
	eCamCoverHighOTS = 33,
	eCamCoverLowScope = 34,
	eCamCoverHighScope = 35,
	eCamCoverLowTakedownOver = 36,
	eCamCoverLowTakedownCorner = 37,
	eCamCoverHighTakedownCorner = 38,
	eCamTakeDisguise = 39,
	eCamOTS = 40,
	eCamOTSHigh = 41,
	eCamOTSLow = 42,
	eCamUnAimedShooting = 43,
	eCamUnAimedShootingHigh = 44,
	eCamUnAimedShootingLow = 45,
	eCamScope = 46,
	eCamScopeHigh = 47,
	eCamScopeLow = 48,
	eCamNumProfiles = 49,
	eCamAll = 50
};
