#pragma once

enum EActorPerceptionSensitivity
{
	APS_AMBIENT_DEAFBLIND = 0,
	APS_AMBIENT_SLEEPING = 1,
	APS_AMBIENT_PREOCCUPIED = 2,
	APS_AMBIENT = 3,
	APS_ALERT = 4,
	APS_COMBAT = 5,
	APS_SPIDER_SENSE = 6,
	APS_NUM_PERCEPTION_LEVELS = 7
};
